# Generated by Django 6.0.6 on 2026-06-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_crm', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('AVAILABLE', 'Available'), ('CLAIMED', 'Claimed'), ('CONTACTED', 'Contacted'), ('IN_PROGRESS', 'In Progress'), ('QUALIFIED', 'Qualified'), ('FOLLOW_UP', 'Follow-up'), ('PROPOSAL_SENT', 'Proposal Sent'), ('NEGOTIATION', 'Negotiation'), ('WON', 'Won'), ('LOST', 'Lost'), ('DUPLICATE', 'Duplicate'), ('INVALID', 'Invalid')], default='NEW', max_length=20),
        ),
    ]
