# Generated by Django 6.0.6 on 2026-06-10 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def sync_completed_status(apps, schema_editor):
    FollowUp = apps.get_model('leads_crm', 'FollowUp')
    FollowUp.objects.filter(completed=True).update(status='COMPLETED')


class Migration(migrations.Migration):

    dependencies = [
        ('leads_crm', '0009_tasks_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_followups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='followup',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10),
        ),
        migrations.AddField(
            model_name='followup',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
        migrations.AddField(
            model_name='followup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='followup_type',
            field=models.CharField(choices=[('CALL', 'Phone Call'), ('EMAIL', 'Email'), ('WHATSAPP', 'WhatsApp'), ('MEETING', 'Meeting'), ('SITE_VISIT', 'Site Visit'), ('DEMO', 'Demo Presentation'), ('QUOTATION', 'Quotation Follow-up'), ('PAYMENT_REMINDER', 'Payment Reminder')], default='CALL', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('IN_PROGRESS', 'In Progress'), ('QUALIFIED', 'Qualified'), ('LOST', 'Lost'), ('WON', 'Won')], default='NEW', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads_crm.followup')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followup_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RunPython(sync_completed_status, migrations.RunPython.noop),
    ]
