# Generated by Django 6.0.6 on 2026-06-10 08:44

from django.db import migrations, models


def seed_default_form_fields(apps, schema_editor):
    LeadForm = apps.get_model('leads_crm', 'LeadForm')
    default_fields = [
        {'id': 'name', 'key': 'name', 'label': 'Full Name', 'type': 'TEXT', 'required': True, 'placeholder': 'e.g. John Doe', 'map_to': 'name'},
        {'id': 'email', 'key': 'email', 'label': 'Email Address', 'type': 'EMAIL', 'required': False, 'placeholder': 'john@example.com', 'map_to': 'email'},
        {'id': 'phone', 'key': 'phone', 'label': 'Phone Number', 'type': 'PHONE', 'required': False, 'placeholder': '+1 555 000 0000', 'map_to': 'phone'},
        {'id': 'notes', 'key': 'notes', 'label': 'Inquiry Details', 'type': 'TEXTAREA', 'required': False, 'placeholder': 'How can we help?', 'map_to': 'notes'},
    ]
    for form in LeadForm.objects.all():
        if not form.form_fields:
            form.form_fields = default_fields
            form.save(update_fields=['form_fields'])


class Migration(migrations.Migration):

    dependencies = [
        ('leads_crm', '0010_followups_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadform',
            name='form_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='leadform',
            name='multi_step_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadform',
            name='thank_you_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leadform',
            name='thank_you_mode',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('MESSAGE', 'Message'), ('REDIRECT', 'Redirect')], default='DEFAULT', max_length=20),
        ),
        migrations.AddField(
            model_name='leadform',
            name='thank_you_redirect_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.RunPython(seed_default_form_fields, migrations.RunPython.noop),
    ]
