# Generated by Django 6.0.6 on 2026-06-10 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_crm', '0012_reports_module'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=255)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('module', models.CharField(choices=[('LEADS', 'Leads'), ('TASKS', 'Tasks'), ('FOLLOWUPS', 'Follow-ups'), ('AUTH', 'Authentication'), ('TEAM', 'Team'), ('COMMISSIONS', 'Commissions'), ('IMPORT', 'Import'), ('EXPORT', 'Export'), ('SETTINGS', 'Settings'), ('FORMS', 'Forms'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('action', models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_DELETED', 'Lead Deleted'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('LEAD_CLAIMED', 'Lead Claimed'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_DELETED', 'Task Deleted'), ('FOLLOWUP_SCHEDULED', 'Follow-up Scheduled'), ('FOLLOWUP_UPDATED', 'Follow-up Updated'), ('FOLLOWUP_COMPLETED', 'Follow-up Completed'), ('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Failed Login Attempt'), ('PASSWORD_CHANGED', 'Password Changed'), ('PROFILE_UPDATED', 'Profile Updated'), ('TEAM_MEMBER_ADDED', 'Team Member Added'), ('TEAM_MEMBER_UPDATED', 'Team Member Updated'), ('ROLE_CHANGED', 'Role Changed'), ('COMMISSION_UPDATED', 'Commission Updated'), ('IMPORT_PERFORMED', 'Import Performed'), ('EXPORT_PERFORMED', 'Export Performed'), ('SETTINGS_UPDATED', 'Settings Updated'), ('FORM_CREATED', 'Form Created'), ('FORM_UPDATED', 'Form Updated'), ('FORM_DELETED', 'Form Deleted')], max_length=40)),
                ('record_type', models.CharField(blank=True, max_length=60)),
                ('record_id', models.CharField(blank=True, max_length=60)),
                ('summary', models.CharField(blank=True, max_length=400)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='leads_crm_a_created_673be7_idx'), models.Index(fields=['module'], name='leads_crm_a_module_66a83a_idx'), models.Index(fields=['action'], name='leads_crm_a_action_b52206_idx'), models.Index(fields=['user'], name='leads_crm_a_user_id_fffd19_idx')],
            },
        ),
    ]
