# Generated by Django 6.0.6 on 2026-06-10 10:08

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads_crm', '0013_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('api_key', models.CharField(blank=True, default='', max_length=500)),
                ('secret_key', models.CharField(blank=True, default='', max_length=500)),
                ('access_token', models.CharField(blank=True, default='', max_length=500)),
                ('webhook_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('CONNECTED', 'Connected'), ('PENDING', 'Pending'), ('DISCONNECTED', 'Disconnected')], default='DISCONNECTED', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='approval_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='auto_calculation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='commission_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage Based'), ('FIXED', 'Fixed Amount'), ('CUSTOM', 'Custom Rules')], default='PERCENTAGE', max_length=20),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='fixed_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='monthly_bonus_rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='team_commission_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commissionsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_setting_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('encryption', models.CharField(choices=[('NONE', 'None'), ('SSL', 'SSL'), ('TLS', 'TLS')], default='TLS', max_length=10)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('templates', models.JSONField(blank=True, default=dict)),
                ('automated_emails_enabled', models.BooleanField(default=True)),
                ('is_connected', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-App'), ('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notifications')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('reminder_minutes', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['notification_type', 'channel'],
                'unique_together': {('notification_type', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_key', models.CharField(max_length=100, unique=True)),
                ('setting_value', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['setting_key'],
            },
        ),
    ]
